# This is a basic workflow to help you get started with Actions

name: Create Forecast

# Controls when the workflow will run
on:
  schedule:
    - cron: "34 9 * * 6"

permissions:
  contents: write  # Explicitly grant write access

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-forecast:
    # The type of runner that the job will run on
    runs-on:  ubuntu-22.04 # R not supported for ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Check out code
      uses: actions/checkout@v4

      - name: Set up R
      uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies
        run: |
          install.packages(c("reshape2", "lubridate", "dplyr"))
        shell: Rscript {0}

      - name: Generate target CSV files
        run: Rscript scripts/pho_all.R 

      
